const Router = require("express").Router()

const BookingRouter = require("./BookingRouter")
const CartRouter = require("./CartRouter")
const CheckoutRouter = require("./CheckoutRouter")
const ContactUsRouter = require("./ContactUsRouter")
const MaincategoryRouter = require("./MaincategoryRouter")
const NewsletterRouter = require("./NewsletterRouter")
const ProductRouter = require("./ProductRouter")
const ResturentRouter = require("./ResturentRouter")
const SubcategoryRouter = require("./SubcategoryRouter")
const TestimonialRouter = require("./TestimonialRouter")
const UserRouter = require("./UserRouter")
const WishlistRouter = require("./WishlistRouter")

Router.use("/maincategory", MaincategoryRouter)
Router.use("/subcategory", SubcategoryRouter)
Router.use("/resturent", ResturentRouter)
Router.use("/testimonial", TestimonialRouter)
Router.use("/contactus", ContactUsRouter)
Router.use("/product", ProductRouter)
Router.use("/newsletter", NewsletterRouter)
Router.use("/user", UserRouter)
Router.use("/cart", CartRouter)
Router.use("/wishlist", WishlistRouter)
Router.use("/booking", BookingRouter)
Router.use("/checkout", CheckoutRouter)

module.exports = Router